name: lando-setup-with-drupal9
recipe: drupal9
config:
  php: '7.3'
  webroot: web/
  drush: ^10
tooling:
  "lint:php:themes":
    service: appserver
    cmd: "composer phpcs:themes"
    description: "Runs php linter against your custom code. Ex: lando lint:php"
  "lint:scss":
    service: node
    cmd: "npm run lint:scss:themes"
    description: "Runs scss linter against your custom code. Ex: lando lint:scss"
  "lint:js":
    service: node
    cmd: "npm run lint:js:themes"
    description: "Runs js linter against your custom code. Ex: lando lint:js"
  "compile:scss":
    service: node
    cmd: "gulp -f=gulp.js"
    description: "Converts scss to css. Ex: lando compile:scss <themes/watchthemes>"
  "npm":
    service: node
    cmd: "npm"
    description: "Runs npm for installing or removing modules. Ex: lando npm <yourcommand>"
proxy:
  appserver:
    - default.lndo.site
services:
  node:
    type: node:14
    build:
      - "cd /app && npm install && npm install -g gulp-cli"
  appserver:
    build:
      - "cd /app && composer install"
      - "/app/vendor/bin/phpcs --config-set installed_paths /app/vendor/drupal/coder/coder_sniffer"
  default:
    type: mysql:5.7
    portforward: true
    config:
      confd: lando/mysql/conf.d
